# For more information: https://laravel.com/docs/sail
version: '3'

services:
  laravel:
    container_name: ${PROJECT_TAG}_laravel
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: laravel_app
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
    networks:
      - app
    depends_on:
      - pgsql

  pgsql:
    container_name: ${PROJECT_TAG}_pgsql
    image: 'postgres:14'
    environment:
      POSTGRES_DB: 'app'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'pgsql:/var/lib/postgresql/data'
      - '.:/var/www/html'
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  pgsql:
    driver: local
